// Sample decks offered on the empty home screen.

export const SAMPLE_DECKS = {
  portuguese: {
    title: 'Numbers in Portuguese',
    front_label: 'Digit',
    back_label: 'Portuguese',
    lang: 'pt-BR',
    color: 'red',
    shape: 'red',
    is_sample: true,
    csv_url: null,
    cards: [
      ['1', 'um|uma'], ['2', 'dois|duas'], ['3', 'três'], ['4', 'quatro'], ['5', 'cinco'],
      ['6', 'seis'], ['7', 'sete'], ['8', 'oito'], ['9', 'nove'], ['10', 'dez'],
    ].map(([front, back]) => ({ front, back })),
  },
  multiplication: {
    title: 'Multiplication tables',
    front_label: 'Problem',
    back_label: 'Answer',
    lang: 'en-US',
    color: 'green',
    shape: 'green',
    is_sample: true,
    csv_url: null,
    // 2 × 2 up to 9 × 9
    cards: Array.from({ length: 8 }, (_, i) => i + 2).flatMap((a) =>
      Array.from({ length: 8 }, (_, j) => j + 2).map((b) => ({ front: `${a} × ${b}`, back: String(a * b) }))),
  },
  flagsWorld: {
    title: 'Flags of the world',
    front_label: 'Flag',
    back_label: 'Country',
    lang: 'en-US',
    color: 'blue',
    shape: 'blue',
    is_sample: true,
    csv_url: null,
    // All 193 UN member states. Images: Wikimedia Commons "Flag of ….svg".
    cards: [
      ['Afghanistan', 'Afghanistan'],
      ['Albania', 'Albania'],
      ['Algeria', 'Algeria'],
      ['Andorra', 'Andorra'],
      ['Angola', 'Angola'],
      ['Antigua and Barbuda', 'Antigua and Barbuda'],
      ['Argentina', 'Argentina'],
      ['Armenia', 'Armenia'],
      ['Australia', 'Australia'],
      ['Austria', 'Austria'],
      ['Azerbaijan', 'Azerbaijan'],
      ['the Bahamas', 'Bahamas|The Bahamas'],
      ['Bahrain', 'Bahrain'],
      ['Bangladesh', 'Bangladesh'],
      ['Barbados', 'Barbados'],
      ['Belarus', 'Belarus'],
      ['Belgium', 'Belgium'],
      ['Belize', 'Belize'],
      ['Benin', 'Benin'],
      ['Bhutan', 'Bhutan'],
      ['Bolivia', 'Bolivia'],
      ['Bosnia and Herzegovina', 'Bosnia and Herzegovina|Bosnia'],
      ['Botswana', 'Botswana'],
      ['Brazil', 'Brazil|Brasil'],
      ['Brunei', 'Brunei'],
      ['Bulgaria', 'Bulgaria'],
      ['Burkina Faso', 'Burkina Faso'],
      ['Burundi', 'Burundi'],
      ['Cambodia', 'Cambodia'],
      ['Cameroon', 'Cameroon'],
      ['Canada', 'Canada'],
      ['Cape Verde', 'Cape Verde|Cabo Verde'],
      ['the Central African Republic', 'Central African Republic'],
      ['Chad', 'Chad'],
      ['Chile', 'Chile'],
      ['the People\'s Republic of China', 'China'],
      ['Colombia', 'Colombia'],
      ['the Comoros', 'Comoros'],
      ['the Democratic Republic of the Congo', 'DR Congo|Democratic Republic of the Congo|Congo-Kinshasa|DRC'],
      ['the Republic of the Congo', 'Republic of the Congo|Congo|Congo-Brazzaville'],
      ['Costa Rica', 'Costa Rica'],
      ['Côte d\'Ivoire', 'Ivory Coast|Côte d\'Ivoire|Cote d\'Ivoire'],
      ['Croatia', 'Croatia'],
      ['Cuba', 'Cuba'],
      ['Cyprus', 'Cyprus'],
      ['the Czech Republic', 'Czech Republic|Czechia'],
      ['Denmark', 'Denmark'],
      ['Djibouti', 'Djibouti'],
      ['Dominica', 'Dominica'],
      ['the Dominican Republic', 'Dominican Republic'],
      ['East Timor', 'East Timor|Timor-Leste'],
      ['Ecuador', 'Ecuador'],
      ['Egypt', 'Egypt'],
      ['El Salvador', 'El Salvador'],
      ['Equatorial Guinea', 'Equatorial Guinea'],
      ['Eritrea', 'Eritrea'],
      ['Estonia', 'Estonia'],
      ['Eswatini', 'Eswatini|Swaziland'],
      ['Ethiopia', 'Ethiopia'],
      ['Fiji', 'Fiji'],
      ['Finland', 'Finland'],
      ['France', 'France'],
      ['Gabon', 'Gabon'],
      ['the Gambia', 'Gambia|The Gambia'],
      ['Georgia', 'Georgia'],
      ['Germany', 'Germany'],
      ['Ghana', 'Ghana'],
      ['Greece', 'Greece'],
      ['Grenada', 'Grenada'],
      ['Guatemala', 'Guatemala'],
      ['Guinea', 'Guinea'],
      ['Guinea-Bissau', 'Guinea-Bissau'],
      ['Guyana', 'Guyana'],
      ['Haiti', 'Haiti'],
      ['Honduras', 'Honduras'],
      ['Hungary', 'Hungary'],
      ['Iceland', 'Iceland'],
      ['India', 'India'],
      ['Indonesia', 'Indonesia'],
      ['Iran', 'Iran'],
      ['Iraq', 'Iraq'],
      ['Ireland', 'Ireland'],
      ['Israel', 'Israel'],
      ['Italy', 'Italy'],
      ['Jamaica', 'Jamaica'],
      ['Japan', 'Japan'],
      ['Jordan', 'Jordan'],
      ['Kazakhstan', 'Kazakhstan'],
      ['Kenya', 'Kenya'],
      ['Kiribati', 'Kiribati'],
      ['Kuwait', 'Kuwait'],
      ['Kyrgyzstan', 'Kyrgyzstan'],
      ['Laos', 'Laos'],
      ['Latvia', 'Latvia'],
      ['Lebanon', 'Lebanon'],
      ['Lesotho', 'Lesotho'],
      ['Liberia', 'Liberia'],
      ['Libya', 'Libya'],
      ['Liechtenstein', 'Liechtenstein'],
      ['Lithuania', 'Lithuania'],
      ['Luxembourg', 'Luxembourg'],
      ['Madagascar', 'Madagascar'],
      ['Malawi', 'Malawi'],
      ['Malaysia', 'Malaysia'],
      ['the Maldives', 'Maldives|The Maldives'],
      ['Mali', 'Mali'],
      ['Malta', 'Malta'],
      ['the Marshall Islands', 'Marshall Islands'],
      ['Mauritania', 'Mauritania'],
      ['Mauritius', 'Mauritius'],
      ['Mexico', 'Mexico'],
      ['the Federated States of Micronesia', 'Micronesia|Federated States of Micronesia'],
      ['Moldova', 'Moldova'],
      ['Monaco', 'Monaco'],
      ['Mongolia', 'Mongolia'],
      ['Montenegro', 'Montenegro'],
      ['Morocco', 'Morocco'],
      ['Mozambique', 'Mozambique'],
      ['Myanmar', 'Myanmar|Burma'],
      ['Namibia', 'Namibia'],
      ['Nauru', 'Nauru'],
      ['Nepal', 'Nepal'],
      ['the Netherlands', 'Netherlands|The Netherlands|Holland'],
      ['New Zealand', 'New Zealand'],
      ['Nicaragua', 'Nicaragua'],
      ['Niger', 'Niger'],
      ['Nigeria', 'Nigeria'],
      ['North Korea', 'North Korea'],
      ['North Macedonia', 'North Macedonia|Macedonia'],
      ['Norway', 'Norway'],
      ['Oman', 'Oman'],
      ['Pakistan', 'Pakistan'],
      ['Palau', 'Palau'],
      ['Panama', 'Panama'],
      ['Papua New Guinea', 'Papua New Guinea'],
      ['Paraguay', 'Paraguay'],
      ['Peru', 'Peru'],
      ['the Philippines', 'Philippines|The Philippines'],
      ['Poland', 'Poland'],
      ['Portugal', 'Portugal'],
      ['Qatar', 'Qatar'],
      ['Romania', 'Romania'],
      ['Russia', 'Russia'],
      ['Rwanda', 'Rwanda'],
      ['Saint Kitts and Nevis', 'Saint Kitts and Nevis|St Kitts and Nevis'],
      ['Saint Lucia', 'Saint Lucia|St Lucia'],
      ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines|St Vincent and the Grenadines'],
      ['Samoa', 'Samoa'],
      ['San Marino', 'San Marino'],
      ['São Tomé and Príncipe', 'São Tomé and Príncipe|Sao Tome and Principe'],
      ['Saudi Arabia', 'Saudi Arabia'],
      ['Senegal', 'Senegal'],
      ['Serbia', 'Serbia'],
      ['Seychelles', 'Seychelles'],
      ['Sierra Leone', 'Sierra Leone'],
      ['Singapore', 'Singapore'],
      ['Slovakia', 'Slovakia'],
      ['Slovenia', 'Slovenia'],
      ['the Solomon Islands', 'Solomon Islands'],
      ['Somalia', 'Somalia'],
      ['South Africa', 'South Africa'],
      ['South Korea', 'South Korea|Korea'],
      ['South Sudan', 'South Sudan'],
      ['Spain', 'Spain'],
      ['Sri Lanka', 'Sri Lanka'],
      ['Sudan', 'Sudan'],
      ['Suriname', 'Suriname'],
      ['Sweden', 'Sweden'],
      ['Switzerland', 'Switzerland'],
      ['Syria', 'Syria'],
      ['Tajikistan', 'Tajikistan'],
      ['Tanzania', 'Tanzania'],
      ['Thailand', 'Thailand'],
      ['Togo', 'Togo'],
      ['Tonga', 'Tonga'],
      ['Trinidad and Tobago', 'Trinidad and Tobago'],
      ['Tunisia', 'Tunisia'],
      ['Turkey', 'Turkey|Türkiye'],
      ['Turkmenistan', 'Turkmenistan'],
      ['Tuvalu', 'Tuvalu'],
      ['Uganda', 'Uganda'],
      ['Ukraine', 'Ukraine'],
      ['the United Arab Emirates', 'United Arab Emirates|UAE'],
      ['the United Kingdom', 'United Kingdom|UK|Great Britain|Britain'],
      ['the United States', 'United States|USA|US|United States of America|America'],
      ['Uruguay', 'Uruguay'],
      ['Uzbekistan', 'Uzbekistan'],
      ['Vanuatu', 'Vanuatu'],
      ['Venezuela', 'Venezuela'],
      ['Vietnam', 'Vietnam|Viet Nam'],
      ['Yemen', 'Yemen'],
      ['Zambia', 'Zambia'],
      ['Zimbabwe', 'Zimbabwe']
    ].map(([file, answers]) => ({ front: `Flag of ${file}.svg`, back: answers })),
  },
  dutchClock: {
    title: 'Telling time in Dutch',
    front_label: 'Clock',
    back_label: 'Dutch',
    lang: 'nl-NL',
    color: 'purple',
    shape: 'purple',
    is_sample: true,
    csv_url: null,
    // The app draws each clock from "clock H:MM". Dutch time is relative to the
    // next hour: 6:30 is "half zeven". Answered by typing.
    cards: [
      ['clock 1:00', 'een uur'],
      ['clock 1:05', 'vijf over een'],
      ['clock 1:10', 'tien over een'],
      ['clock 1:15', 'kwart over een'],
      ['clock 1:20', 'tien voor half twee|twintig over een'],
      ['clock 1:25', 'vijf voor half twee|vijfentwintig over een'],
      ['clock 1:30', 'half twee'],
      ['clock 1:35', 'vijf over half twee|vijfentwintig voor twee'],
      ['clock 1:40', 'tien over half twee|twintig voor twee'],
      ['clock 1:45', 'kwart voor twee'],
      ['clock 1:50', 'tien voor twee'],
      ['clock 1:55', 'vijf voor twee'],
      ['clock 2:00', 'twee uur'],
      ['clock 2:05', 'vijf over twee'],
      ['clock 2:10', 'tien over twee'],
      ['clock 2:15', 'kwart over twee'],
      ['clock 2:20', 'tien voor half drie|twintig over twee'],
      ['clock 2:25', 'vijf voor half drie|vijfentwintig over twee'],
      ['clock 2:30', 'half drie'],
      ['clock 2:35', 'vijf over half drie|vijfentwintig voor drie'],
      ['clock 2:40', 'tien over half drie|twintig voor drie'],
      ['clock 2:45', 'kwart voor drie'],
      ['clock 2:50', 'tien voor drie'],
      ['clock 2:55', 'vijf voor drie'],
      ['clock 3:00', 'drie uur'],
      ['clock 3:05', 'vijf over drie'],
      ['clock 3:10', 'tien over drie'],
      ['clock 3:15', 'kwart over drie'],
      ['clock 3:20', 'tien voor half vier|twintig over drie'],
      ['clock 3:25', 'vijf voor half vier|vijfentwintig over drie'],
      ['clock 3:30', 'half vier'],
      ['clock 3:35', 'vijf over half vier|vijfentwintig voor vier'],
      ['clock 3:40', 'tien over half vier|twintig voor vier'],
      ['clock 3:45', 'kwart voor vier'],
      ['clock 3:50', 'tien voor vier'],
      ['clock 3:55', 'vijf voor vier'],
      ['clock 4:00', 'vier uur'],
      ['clock 4:05', 'vijf over vier'],
      ['clock 4:10', 'tien over vier'],
      ['clock 4:15', 'kwart over vier'],
      ['clock 4:20', 'tien voor half vijf|twintig over vier'],
      ['clock 4:25', 'vijf voor half vijf|vijfentwintig over vier'],
      ['clock 4:30', 'half vijf'],
      ['clock 4:35', 'vijf over half vijf|vijfentwintig voor vijf'],
      ['clock 4:40', 'tien over half vijf|twintig voor vijf'],
      ['clock 4:45', 'kwart voor vijf'],
      ['clock 4:50', 'tien voor vijf'],
      ['clock 4:55', 'vijf voor vijf'],
      ['clock 5:00', 'vijf uur'],
      ['clock 5:05', 'vijf over vijf'],
      ['clock 5:10', 'tien over vijf'],
      ['clock 5:15', 'kwart over vijf'],
      ['clock 5:20', 'tien voor half zes|twintig over vijf'],
      ['clock 5:25', 'vijf voor half zes|vijfentwintig over vijf'],
      ['clock 5:30', 'half zes'],
      ['clock 5:35', 'vijf over half zes|vijfentwintig voor zes'],
      ['clock 5:40', 'tien over half zes|twintig voor zes'],
      ['clock 5:45', 'kwart voor zes'],
      ['clock 5:50', 'tien voor zes'],
      ['clock 5:55', 'vijf voor zes'],
      ['clock 6:00', 'zes uur'],
      ['clock 6:05', 'vijf over zes'],
      ['clock 6:10', 'tien over zes'],
      ['clock 6:15', 'kwart over zes'],
      ['clock 6:20', 'tien voor half zeven|twintig over zes'],
      ['clock 6:25', 'vijf voor half zeven|vijfentwintig over zes'],
      ['clock 6:30', 'half zeven'],
      ['clock 6:35', 'vijf over half zeven|vijfentwintig voor zeven'],
      ['clock 6:40', 'tien over half zeven|twintig voor zeven'],
      ['clock 6:45', 'kwart voor zeven'],
      ['clock 6:50', 'tien voor zeven'],
      ['clock 6:55', 'vijf voor zeven'],
      ['clock 7:00', 'zeven uur'],
      ['clock 7:05', 'vijf over zeven'],
      ['clock 7:10', 'tien over zeven'],
      ['clock 7:15', 'kwart over zeven'],
      ['clock 7:20', 'tien voor half acht|twintig over zeven'],
      ['clock 7:25', 'vijf voor half acht|vijfentwintig over zeven'],
      ['clock 7:30', 'half acht'],
      ['clock 7:35', 'vijf over half acht|vijfentwintig voor acht'],
      ['clock 7:40', 'tien over half acht|twintig voor acht'],
      ['clock 7:45', 'kwart voor acht'],
      ['clock 7:50', 'tien voor acht'],
      ['clock 7:55', 'vijf voor acht'],
      ['clock 8:00', 'acht uur'],
      ['clock 8:05', 'vijf over acht'],
      ['clock 8:10', 'tien over acht'],
      ['clock 8:15', 'kwart over acht'],
      ['clock 8:20', 'tien voor half negen|twintig over acht'],
      ['clock 8:25', 'vijf voor half negen|vijfentwintig over acht'],
      ['clock 8:30', 'half negen'],
      ['clock 8:35', 'vijf over half negen|vijfentwintig voor negen'],
      ['clock 8:40', 'tien over half negen|twintig voor negen'],
      ['clock 8:45', 'kwart voor negen'],
      ['clock 8:50', 'tien voor negen'],
      ['clock 8:55', 'vijf voor negen'],
      ['clock 9:00', 'negen uur'],
      ['clock 9:05', 'vijf over negen'],
      ['clock 9:10', 'tien over negen'],
      ['clock 9:15', 'kwart over negen'],
      ['clock 9:20', 'tien voor half tien|twintig over negen'],
      ['clock 9:25', 'vijf voor half tien|vijfentwintig over negen'],
      ['clock 9:30', 'half tien'],
      ['clock 9:35', 'vijf over half tien|vijfentwintig voor tien'],
      ['clock 9:40', 'tien over half tien|twintig voor tien'],
      ['clock 9:45', 'kwart voor tien'],
      ['clock 9:50', 'tien voor tien'],
      ['clock 9:55', 'vijf voor tien'],
      ['clock 10:00', 'tien uur'],
      ['clock 10:05', 'vijf over tien'],
      ['clock 10:10', 'tien over tien'],
      ['clock 10:15', 'kwart over tien'],
      ['clock 10:20', 'tien voor half elf|twintig over tien'],
      ['clock 10:25', 'vijf voor half elf|vijfentwintig over tien'],
      ['clock 10:30', 'half elf'],
      ['clock 10:35', 'vijf over half elf|vijfentwintig voor elf'],
      ['clock 10:40', 'tien over half elf|twintig voor elf'],
      ['clock 10:45', 'kwart voor elf'],
      ['clock 10:50', 'tien voor elf'],
      ['clock 10:55', 'vijf voor elf'],
      ['clock 11:00', 'elf uur'],
      ['clock 11:05', 'vijf over elf'],
      ['clock 11:10', 'tien over elf'],
      ['clock 11:15', 'kwart over elf'],
      ['clock 11:20', 'tien voor half twaalf|twintig over elf'],
      ['clock 11:25', 'vijf voor half twaalf|vijfentwintig over elf'],
      ['clock 11:30', 'half twaalf'],
      ['clock 11:35', 'vijf over half twaalf|vijfentwintig voor twaalf'],
      ['clock 11:40', 'tien over half twaalf|twintig voor twaalf'],
      ['clock 11:45', 'kwart voor twaalf'],
      ['clock 11:50', 'tien voor twaalf'],
      ['clock 11:55', 'vijf voor twaalf'],
      ['clock 12:00', 'twaalf uur'],
      ['clock 12:05', 'vijf over twaalf'],
      ['clock 12:10', 'tien over twaalf'],
      ['clock 12:15', 'kwart over twaalf'],
      ['clock 12:20', 'tien voor half een|twintig over twaalf'],
      ['clock 12:25', 'vijf voor half een|vijfentwintig over twaalf'],
      ['clock 12:30', 'half een'],
      ['clock 12:35', 'vijf over half een|vijfentwintig voor een'],
      ['clock 12:40', 'tien over half een|twintig voor een'],
      ['clock 12:45', 'kwart voor een'],
      ['clock 12:50', 'tien voor een'],
      ['clock 12:55', 'vijf voor een']
    ].map(([front, back]) => ({ front, back })),
  },
};

/** What the ready-made list shows, in order. */
export const READY_MADE = [
  { key: 'portuguese', title: 'Numbers in Portuguese', color: 'red' },
  { key: 'multiplication', title: 'Multiplication tables', color: 'green' },
  { key: 'flagsWorld', title: 'Flags of the world', color: 'blue' },
  { key: 'dutchClock', title: 'Telling time in Dutch', color: 'purple' },
];
