// Sample decks offered on the empty home screen.

export const SAMPLE_DECKS = {
  portuguese: {
    title: 'Numbers in Portuguese',
    front_label: 'Digit',
    back_label: 'Portuguese',
    lang: 'pt-BR',
    color: 'red',
    shape: 'red',
    is_sample: true,
    csv_url: null,
    cards: [
      ['1', 'um|uma'], ['2', 'dois|duas'], ['3', 'três'], ['4', 'quatro'], ['5', 'cinco'],
      ['6', 'seis'], ['7', 'sete'], ['8', 'oito'], ['9', 'nove'], ['10', 'dez'],
    ].map(([front, back]) => ({ front, back })),
  },
  multiplication: {
    title: 'Multiplication tables',
    front_label: 'Problem',
    back_label: 'Answer',
    lang: 'en-US',
    color: 'green',
    shape: 'green',
    is_sample: true,
    csv_url: null,
    // 2 × 2 up to 9 × 9
    cards: Array.from({ length: 8 }, (_, i) => i + 2).flatMap((a) =>
      Array.from({ length: 8 }, (_, j) => j + 2).map((b) => ({ front: `${a} × ${b}`, back: String(a * b) }))),
  },
  belgianSigns: {
    title: 'Belgian road signs',
    front_label: 'Sign',
    back_label: 'Meaning',
    lang: 'en-US',
    color: 'yellow',
    shape: 'yellow',
    is_sample: true,
    csv_url: null,
    // Current Belgian highway code (Royal Decree of 1 December 1975), meanings
    // as listed on Wikipedia's "Road signs in Belgium". Images: Wikimedia Commons.
    // The new Code of the public road (from June 2027) renumbers some signs.
    cards: [
      ['A1a', 'Bend to the left'],
      ['A1b', 'Bend to the right'],
      ['A1c', 'Double bend, first to the left'],
      ['A3', 'Steep descent'],
      ['A5', 'Steep ascent'],
      ['A7a', 'Road narrows'],
      ['A13', 'Uneven road'],
      ['A14', 'Road bump'],
      ['A15', 'Slippery road'],
      ['A21', 'Pedestrian crossing'],
      ['A23', 'Children'],
      ['A25', 'Cyclists'],
      ['A27', 'Deer crossing'],
      ['A31', 'Roadworks'],
      ['A33', 'Traffic signals'],
      ['A37', 'Crosswinds'],
      ['A39', 'Two-way traffic'],
      ['A41', 'Railroad crossing ahead with gates or barriers'],
      ['A43', 'Railroad crossing ahead without gates or barriers'],
      ['A51', 'Other dangers'],
      ['B1', 'Yield'],
      ['B5', 'Stop'],
      ['B9', 'Priority road'],
      ['B11', 'End of priority road'],
      ['B15', 'Intersection with priority'],
      ['B17', 'Intersection with priority to the right'],
      ['B19', 'Yield to oncoming traffic'],
      ['B21', 'Priority over oncoming traffic'],
      ['C1', 'Do not enter'],
      ['C3', 'No vehicles in both directions'],
      ['C11', 'No entry for bicycles'],
      ['C19', 'No entry for pedestrians'],
      ['C21', 'Weight limit'],
      ['C29', 'Height limit'],
      ['C31a', 'No left turn'],
      ['C31b', 'No right turn'],
      ['C33', 'No U-turn'],
      ['C35', 'No overtaking'],
      ['C43', 'Maximum speed'],
      ['C45', 'End of the maximum speed restriction'],
      ['C46', 'End of the restrictions imposed on moving vehicles'],
      ['D1a', 'Ahead only'],
      ['D5', 'Roundabout'],
      ['D7', 'Cycleway'],
      ['D11', 'Footpath'],
      ['E1', 'No parking'],
      ['E3', 'No stopping'],
      ['F4a', 'Start of a 30 km/h speed zone'],
      ['F5', 'Start of a motorway'],
      ['F7', 'End of a motorway'],
      ['F12a', 'Start of a living street'],
      ['F19', 'One-way road'],
      ['F45', 'Dead end'],
      ['F49', 'Pedestrian crossing']
    ].map(([code, meaning]) => ({ front: `Belgian road sign ${code}.svg`, back: meaning })),
  },
  flagsWorld: {
    title: 'Flags of the world',
    front_label: 'Flag',
    back_label: 'Country',
    lang: 'en-US',
    color: 'blue',
    shape: 'blue',
    is_sample: true,
    csv_url: null,
    // All 193 UN member states. Images: Wikimedia Commons "Flag of ….svg".
    cards: [
      ['Afghanistan', 'Afghanistan'],
      ['Albania', 'Albania'],
      ['Algeria', 'Algeria'],
      ['Andorra', 'Andorra'],
      ['Angola', 'Angola'],
      ['Antigua and Barbuda', 'Antigua and Barbuda'],
      ['Argentina', 'Argentina'],
      ['Armenia', 'Armenia'],
      ['Australia', 'Australia'],
      ['Austria', 'Austria'],
      ['Azerbaijan', 'Azerbaijan'],
      ['the Bahamas', 'Bahamas|The Bahamas'],
      ['Bahrain', 'Bahrain'],
      ['Bangladesh', 'Bangladesh'],
      ['Barbados', 'Barbados'],
      ['Belarus', 'Belarus'],
      ['Belgium', 'Belgium'],
      ['Belize', 'Belize'],
      ['Benin', 'Benin'],
      ['Bhutan', 'Bhutan'],
      ['Bolivia', 'Bolivia'],
      ['Bosnia and Herzegovina', 'Bosnia and Herzegovina|Bosnia'],
      ['Botswana', 'Botswana'],
      ['Brazil', 'Brazil|Brasil'],
      ['Brunei', 'Brunei'],
      ['Bulgaria', 'Bulgaria'],
      ['Burkina Faso', 'Burkina Faso'],
      ['Burundi', 'Burundi'],
      ['Cambodia', 'Cambodia'],
      ['Cameroon', 'Cameroon'],
      ['Canada', 'Canada'],
      ['Cape Verde', 'Cape Verde|Cabo Verde'],
      ['the Central African Republic', 'Central African Republic'],
      ['Chad', 'Chad'],
      ['Chile', 'Chile'],
      ['the People\'s Republic of China', 'China'],
      ['Colombia', 'Colombia'],
      ['the Comoros', 'Comoros'],
      ['the Democratic Republic of the Congo', 'DR Congo|Democratic Republic of the Congo|Congo-Kinshasa|DRC'],
      ['the Republic of the Congo', 'Republic of the Congo|Congo|Congo-Brazzaville'],
      ['Costa Rica', 'Costa Rica'],
      ['Côte d\'Ivoire', 'Ivory Coast|Côte d\'Ivoire|Cote d\'Ivoire'],
      ['Croatia', 'Croatia'],
      ['Cuba', 'Cuba'],
      ['Cyprus', 'Cyprus'],
      ['the Czech Republic', 'Czech Republic|Czechia'],
      ['Denmark', 'Denmark'],
      ['Djibouti', 'Djibouti'],
      ['Dominica', 'Dominica'],
      ['the Dominican Republic', 'Dominican Republic'],
      ['East Timor', 'East Timor|Timor-Leste'],
      ['Ecuador', 'Ecuador'],
      ['Egypt', 'Egypt'],
      ['El Salvador', 'El Salvador'],
      ['Equatorial Guinea', 'Equatorial Guinea'],
      ['Eritrea', 'Eritrea'],
      ['Estonia', 'Estonia'],
      ['Eswatini', 'Eswatini|Swaziland'],
      ['Ethiopia', 'Ethiopia'],
      ['Fiji', 'Fiji'],
      ['Finland', 'Finland'],
      ['France', 'France'],
      ['Gabon', 'Gabon'],
      ['the Gambia', 'Gambia|The Gambia'],
      ['Georgia', 'Georgia'],
      ['Germany', 'Germany'],
      ['Ghana', 'Ghana'],
      ['Greece', 'Greece'],
      ['Grenada', 'Grenada'],
      ['Guatemala', 'Guatemala'],
      ['Guinea', 'Guinea'],
      ['Guinea-Bissau', 'Guinea-Bissau'],
      ['Guyana', 'Guyana'],
      ['Haiti', 'Haiti'],
      ['Honduras', 'Honduras'],
      ['Hungary', 'Hungary'],
      ['Iceland', 'Iceland'],
      ['India', 'India'],
      ['Indonesia', 'Indonesia'],
      ['Iran', 'Iran'],
      ['Iraq', 'Iraq'],
      ['Ireland', 'Ireland'],
      ['Israel', 'Israel'],
      ['Italy', 'Italy'],
      ['Jamaica', 'Jamaica'],
      ['Japan', 'Japan'],
      ['Jordan', 'Jordan'],
      ['Kazakhstan', 'Kazakhstan'],
      ['Kenya', 'Kenya'],
      ['Kiribati', 'Kiribati'],
      ['Kuwait', 'Kuwait'],
      ['Kyrgyzstan', 'Kyrgyzstan'],
      ['Laos', 'Laos'],
      ['Latvia', 'Latvia'],
      ['Lebanon', 'Lebanon'],
      ['Lesotho', 'Lesotho'],
      ['Liberia', 'Liberia'],
      ['Libya', 'Libya'],
      ['Liechtenstein', 'Liechtenstein'],
      ['Lithuania', 'Lithuania'],
      ['Luxembourg', 'Luxembourg'],
      ['Madagascar', 'Madagascar'],
      ['Malawi', 'Malawi'],
      ['Malaysia', 'Malaysia'],
      ['the Maldives', 'Maldives|The Maldives'],
      ['Mali', 'Mali'],
      ['Malta', 'Malta'],
      ['the Marshall Islands', 'Marshall Islands'],
      ['Mauritania', 'Mauritania'],
      ['Mauritius', 'Mauritius'],
      ['Mexico', 'Mexico'],
      ['the Federated States of Micronesia', 'Micronesia|Federated States of Micronesia'],
      ['Moldova', 'Moldova'],
      ['Monaco', 'Monaco'],
      ['Mongolia', 'Mongolia'],
      ['Montenegro', 'Montenegro'],
      ['Morocco', 'Morocco'],
      ['Mozambique', 'Mozambique'],
      ['Myanmar', 'Myanmar|Burma'],
      ['Namibia', 'Namibia'],
      ['Nauru', 'Nauru'],
      ['Nepal', 'Nepal'],
      ['the Netherlands', 'Netherlands|The Netherlands|Holland'],
      ['New Zealand', 'New Zealand'],
      ['Nicaragua', 'Nicaragua'],
      ['Niger', 'Niger'],
      ['Nigeria', 'Nigeria'],
      ['North Korea', 'North Korea'],
      ['North Macedonia', 'North Macedonia|Macedonia'],
      ['Norway', 'Norway'],
      ['Oman', 'Oman'],
      ['Pakistan', 'Pakistan'],
      ['Palau', 'Palau'],
      ['Panama', 'Panama'],
      ['Papua New Guinea', 'Papua New Guinea'],
      ['Paraguay', 'Paraguay'],
      ['Peru', 'Peru'],
      ['the Philippines', 'Philippines|The Philippines'],
      ['Poland', 'Poland'],
      ['Portugal', 'Portugal'],
      ['Qatar', 'Qatar'],
      ['Romania', 'Romania'],
      ['Russia', 'Russia'],
      ['Rwanda', 'Rwanda'],
      ['Saint Kitts and Nevis', 'Saint Kitts and Nevis|St Kitts and Nevis'],
      ['Saint Lucia', 'Saint Lucia|St Lucia'],
      ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines|St Vincent and the Grenadines'],
      ['Samoa', 'Samoa'],
      ['San Marino', 'San Marino'],
      ['São Tomé and Príncipe', 'São Tomé and Príncipe|Sao Tome and Principe'],
      ['Saudi Arabia', 'Saudi Arabia'],
      ['Senegal', 'Senegal'],
      ['Serbia', 'Serbia'],
      ['Seychelles', 'Seychelles'],
      ['Sierra Leone', 'Sierra Leone'],
      ['Singapore', 'Singapore'],
      ['Slovakia', 'Slovakia'],
      ['Slovenia', 'Slovenia'],
      ['the Solomon Islands', 'Solomon Islands'],
      ['Somalia', 'Somalia'],
      ['South Africa', 'South Africa'],
      ['South Korea', 'South Korea|Korea'],
      ['South Sudan', 'South Sudan'],
      ['Spain', 'Spain'],
      ['Sri Lanka', 'Sri Lanka'],
      ['Sudan', 'Sudan'],
      ['Suriname', 'Suriname'],
      ['Sweden', 'Sweden'],
      ['Switzerland', 'Switzerland'],
      ['Syria', 'Syria'],
      ['Tajikistan', 'Tajikistan'],
      ['Tanzania', 'Tanzania'],
      ['Thailand', 'Thailand'],
      ['Togo', 'Togo'],
      ['Tonga', 'Tonga'],
      ['Trinidad and Tobago', 'Trinidad and Tobago'],
      ['Tunisia', 'Tunisia'],
      ['Turkey', 'Turkey|Türkiye'],
      ['Turkmenistan', 'Turkmenistan'],
      ['Tuvalu', 'Tuvalu'],
      ['Uganda', 'Uganda'],
      ['Ukraine', 'Ukraine'],
      ['the United Arab Emirates', 'United Arab Emirates|UAE'],
      ['the United Kingdom', 'United Kingdom|UK|Great Britain|Britain'],
      ['the United States', 'United States|USA|US|United States of America|America'],
      ['Uruguay', 'Uruguay'],
      ['Uzbekistan', 'Uzbekistan'],
      ['Vanuatu', 'Vanuatu'],
      ['Venezuela', 'Venezuela'],
      ['Vietnam', 'Vietnam|Viet Nam'],
      ['Yemen', 'Yemen'],
      ['Zambia', 'Zambia'],
      ['Zimbabwe', 'Zimbabwe']
    ].map(([file, answers]) => ({ front: `Flag of ${file}.svg`, back: answers })),
  },
};

/** What the ready-made list shows, in order. */
export const READY_MADE = [
  { key: 'portuguese', title: 'Numbers in Portuguese', color: 'red' },
  { key: 'multiplication', title: 'Multiplication tables', color: 'green' },
  { key: 'belgianSigns', title: 'Belgian road signs', color: 'yellow' },
  { key: 'flagsWorld', title: 'Flags of the world', color: 'blue' },
];
