import { defineConfig, createServer } from 'vite';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import react from '@vitejs/plugin-react';

// Each build gets a version stamp. It's baked into the app and also written to
// /version.json, so a running app can tell when a newer build has been deployed.
const BUILD_VERSION = Date.now().toString(36);

const versionFile = () => ({
  name: 'alle-version-file',
  generateBundle() {
    this.emitFile({ type: 'asset', fileName: 'version.json', source: JSON.stringify({ version: BUILD_VERSION }) });
  },
});


// The tour scenes, published for the website (Help page + homepage guides):
//   /embed/scenes.json  { version, scenes: { welcome: "<div …>", … } }
//   /embed/scenes.css   Alle's tokens + the scene styles, scoped to .alle-scene
// The website loads both, so it always shows exactly what the app shows.
function scopeTokens(css) {
  // :root → .alle-scene; the dark theme follows the visitor's system setting
  // there, unless the page adds .alle-scene--light (pages that are light only).
  const darkStart = css.indexOf(':root[data-theme="dark"]');
  const light = css.slice(0, darkStart).replace(/:root\s*\{/, '.alle-scene {');
  const dark = css.slice(darkStart).replace(/:root\[data-theme="dark"\]\s*\{/, '.alle-scene:not(.alle-scene--light) {');
  return `${light}\n@media (prefers-color-scheme: dark) {\n${dark}\n}\n`;
}
const sceneEmbed = () => {
  let outDir = 'dist';
  return {
    name: 'alle-scene-embed',
    apply: 'build',
    configResolved(c) { outDir = resolve(c.root, c.build.outDir); },
    async closeBundle() {
      const server = await createServer({
        configFile: false, plugins: [react()], logLevel: 'error',
        server: { middlewareMode: true, hmr: false }, appType: 'custom',
      });
      try {
        const { renderScenes } = await server.ssrLoadModule('/src/embed/render.jsx');
        const read = (f) => readFileSync(resolve('src', f), 'utf8');
        const css = [
          `/* Generated by the Alle app build (${BUILD_VERSION}). Edit src/styles/scenes.css in alle-app, not this file. */`,
          scopeTokens(read('styles/tokens.css')),
          read('embed/base.css'),
          read('styles/scenes.css'),
        ].join('\n');
        mkdirSync(resolve(outDir, 'embed'), { recursive: true });
        writeFileSync(resolve(outDir, 'embed/scenes.css'), css);
        writeFileSync(resolve(outDir, 'embed/scenes.json'), JSON.stringify({ version: BUILD_VERSION, scenes: renderScenes() }));
      } finally {
        await server.close();
      }
    },
  };
};

export default defineConfig({
  plugins: [react(), versionFile(), sceneEmbed()],
  define: { __APP_VERSION__: JSON.stringify(BUILD_VERSION) },
  server: { host: true },
});
